---
- name: Add cassandra apt key
  become: yes
  become_user: root
  apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    id: A278B781FE4B2BDA
    state: present
  register: add_repository_key
  ignore_errors: "{{ cassandra_apt_ignore_key_error }}"

- name: Add cassandra repository
  become: yes
  become_user: root
  apt_repository:
    repo: "{{ cassandra_apt_repository }}"
    state: present
    update_cache: true

- name: Install cassandra
  become: yes
  become_user: root
  apt:
    name: cassandra
    state: present

- name: Copy the cassandra.yaml configuration file
  become: yes
  become_user: root
  template:
    src: cassandra.yaml
    dest: /etc/cassandra/cassandra.yaml
    mode: 0755

- name: Copy the cassandra rack configuration file
  become: yes
  become_user: root
  template:
    src: cassandra-rackdc.properties
    dest: /etc/cassandra/cassandra-rackdc.properties
    mode: 0755

- name: Restart cassandra
  become: yes
  become_user: root
  service:
    name: cassandra
    state: started
    enabled: yes

- name: Initilize keyspace
  run_once: true
  shell: |
    sleep 15
    echo "CREATE KEYSPACE IF NOT EXISTS \"{{ cassandra_keyspace }}\" WITH replication = {'class': 'SimpleStrategy', 'replication_factor': {{ cassandra_replication_factor }} };" >> {{ home_path }}/init.cql
    cqlsh -f {{ home_path }}/init.cql {{ cassandra_hosts | first }}

